version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps:"
    groups:
      spark-example-nuget:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      spark-example-nuget-major:
        patterns:
          - "*"
        update-types:
          - "major"
